/* Generated By:JavaCC: Do not edit this line. GMLConstants.java */
package mayday.graphviewer.datasources.gml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LEFTB = 8;
  /** RegularExpression Id. */
  int RIGHTB = 9;
  /** RegularExpression Id. */
  int KEY = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int INSTRING = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int SIGN = 15;
  /** RegularExpression Id. */
  int REAL = 16;
  /** RegularExpression Id. */
  int MANTISSA = 17;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 7>",
    "\"[\"",
    "\"]\"",
    "<KEY>",
    "<STRING>",
    "<INSTRING>",
    "<DIGIT>",
    "<INTEGER>",
    "<SIGN>",
    "<REAL>",
    "<MANTISSA>",
  };

}
